title: "cnx has spoken"
description: "A simple Jekyll theme with a JSON-like index."

highlighter: rouge
rouge:
  theme: github

collections:
  my_posts:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_my_posts/en"
    values:
      lang: en
  - scope:
      path: "_my_posts/pt"
    values:
      lang: pt
      
markdown: kramdown
kramdown:
  input: GFM